/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import com.mycompany.mantenimiento_paula.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import profesor.profe_addInci;
import profesor.profe_screen;
import tecnico.tec_modifyIncidencia;

/**
 *
 * @author damA
 */
public class modify_usuario extends javax.swing.JDialog {
     // Conexion a la bbdd
    Conectar conectar = new Conectar();
    // Variable para el id del usuario
    String usuario;
    String id;
    // Variable para el id de la incidencia
    String idIn;

    /**
     * Creates new form modify_usuario
     */
    public modify_usuario(javax.swing.JDialog parent, boolean modal, String user, String idInci) {
        super(parent, modal);
        initComponents();
        
        conectar.getConexion();

        usuario = user;
        idIn = idInci;
        
        rellenarRol();
        rellenarDepa();
        
        rellenarDatos();
        
        saberId();
        icono();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }
    
     // Metodo del icono
    public void icono(){
        ImageIcon img = new ImageIcon("src\\main\\java\\resources\\icon.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcb_rol = new javax.swing.JComboBox<>();
        jpass_usuario = new javax.swing.JPasswordField();
        jcb_departamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxt_nombreCompleto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jlbl_rol = new javax.swing.JLabel();
        jlbl_departamento = new javax.swing.JLabel();
        jbtn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña:");

        jcb_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_rolActionPerformed(evt);
            }
        });

        jcb_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_departamentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Nombre Completo:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Rol:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de Usuario:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo Usuario");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Departamento:");

        jbtn_volver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_nombreCompleto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_nombre)
                            .addComponent(jpass_usuario)
                            .addComponent(jtxt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jcb_departamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_departamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbl_rol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcb_rol, 0, 120, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpass_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbl_rol)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jlbl_departamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbtn_volver))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modificarUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcb_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_rolActionPerformed
       rellenarRol();
    }//GEN-LAST:event_jcb_rolActionPerformed

    private void jcb_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_departamentoActionPerformed
        rellenarDepa();
    }//GEN-LAST:event_jcb_departamentoActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.setVisible(false);
        ver_profesores screen = new ver_profesores(this, true, usuario);
        screen.setVisible(true);
    }//GEN-LAST:event_jbtn_volverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JComboBox<String> jcb_departamento;
    private javax.swing.JComboBox<String> jcb_rol;
    private javax.swing.JLabel jlbl_departamento;
    private javax.swing.JLabel jlbl_rol;
    private javax.swing.JPasswordField jpass_usuario;
    private javax.swing.JTextField jtxt_email;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_nombreCompleto;
    // End of variables declaration//GEN-END:variables

    private void rellenarRol() {
        Connection conexion = conectar.getConexion();
        
        try {
            
            PreparedStatement ps = conexion.prepareStatement("SELECT distinct id_rol, rol FROM fp_rol");
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                
                jcb_rol.addItem(rs.getString("id_rol") + " - " + rs.getString("rol"));
            }
            
            conexion.close();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void rellenarDepa() {
         Connection conexion = conectar.getConexion();
        
        try {
            
            PreparedStatement ps = conexion.prepareStatement("SELECT distinct id_departamento, departamento FROM fp_departamento");
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                
                jcb_departamento.addItem(rs.getString("id_departamento") + " - " + rs.getString("departamento"));
            }
            
            conexion.close();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void rellenarDatos() {
        Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("select p.id_profesor, p.login, p.password, p.nombre_completo, p.email, p.activo, r.rol, d.departamento\n"
                    + "from fp_profesor p inner join fp_rol r\n"
                    + "on p.id_rol = r.id_rol inner join fp_departamento d\n"
                    + "on p.id_departamento = d.id_departamento where p.id_profesor = '"+idIn+"'");

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                jtxt_nombre.setText(rs.getString(2));
                jpass_usuario.setText(rs.getString(3));
                jtxt_nombreCompleto.setText(rs.getString(4));
                jtxt_email.setText(rs.getString(5));
                jlbl_rol.setText("Anterior: " + rs.getString(7));
                jlbl_departamento.setText("Anterior: " + rs.getString(8));
            }

            conexion.close();

        } catch (SQLException ex) {
            Logger.getLogger(profe_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saberId() {
       Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("select id_profesor from fp_profesor where login = '" + usuario + "';");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                id = rs.getString(1);
            }

            conexion.close();

        } catch (SQLException ex) {
            Logger.getLogger(tec_modifyIncidencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void modificarUsuario() {
         String login = jtxt_nombre.getText();
        String pass = String.valueOf(jpass_usuario.getPassword());
        String nombre = jtxt_nombreCompleto.getText();
        String email = jtxt_email.getText();
        String activo = "1";
        String rol = (String) jcb_rol.getSelectedItem();
        String depa = (String) jcb_departamento.getSelectedItem();
        
        String[] r = rol.toString().split(" - ");
        String rolis = r[0];
        String[] d = depa.toString().split(" - ");
        String depas = d[0];

        Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("UPDATE fp_profesor set id_profesor='" + idIn + "',login='" + login + "',password='" + pass + "',nombre_completo='" + nombre + "',email='" + email + "',activo='" + activo + "',id_rol='" + rolis + "',id_departamento='" + depas + "' where id_profesor = '" + idIn + "'");
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos insertados.");

            conexion.close();

        } catch (SQLException ex) {

            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }
}
