/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecnico;

import administrador.add_usuario;
import administrador.ver_profesores;
import com.mycompany.mantenimiento_paula.Conectar;
import com.mycompany.mantenimiento_paula.ayuda;
import com.mycompany.mantenimiento_paula.main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import profesor.enviarCorreo;

/**
 *
 * @author damA
 */
public class tec_screen extends javax.swing.JDialog {
    Conectar conectar = new Conectar();
    // Variable para guardar el id del usuario
    String usuario;
    String id;
    // Modelo de la tabla 
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form screenTecnico
     */
    public tec_screen(javax.swing.JDialog parent, boolean modal, String user) {        
        conectar.getConexion();        
        initComponents();
        usuario = user;
        saberId();
        verIncidencias();
        icono();        
        popmenu();
        
         setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // X de la pantalla
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                new main().setVisible(true);
            }
        });
    }
    
    // Metodo del icono
    public void icono() {
        ImageIcon img = new ImageIcon("src\\main\\java\\resources\\icon.png");
        this.setIconImage(img.getImage());
    }
    
    // JPopUp Menu
    private void popmenu(){        
       // Menu Item con Modificar Incidencia
       JMenuItem modificar = new JMenuItem ("Modificar incidencia");
       jppm.add(modificar);
       // Menu item con Eliminar Incidencia
       JMenuItem borrar = new JMenuItem ("Eliminar incidencia");
       
       jppm.add(borrar);       
       jt_tecnico.setComponentPopupMenu(jppm);
       
       modificar.addActionListener(new ActionListener() { 
           @Override
           public void actionPerformed(ActionEvent e) {               
               String idInci = (String) dtm.getValueAt(jt_tecnico.getSelectedRow(), 0);              
               tec_modifyIncidencia add = new tec_modifyIncidencia(tec_screen.this, true, usuario, idInci);
               add.setVisible(true);                
               verIncidencias();
           }
       });
       
       borrar.addActionListener(new ActionListener() { 
           @Override
           public void actionPerformed(ActionEvent e) {
               deleteRow();             
               verIncidencias();
           }
       });
      
    }
    
    // Metodo para eliminar una incidencia del pop up menu
    private void deleteRow() {
        Connection conexion = conectar.getConexion();        
        var selectedRow = jt_tecnico.getValueAt(jt_tecnico.getSelectedRow(), 0);        
        try {
            PreparedStatement ps = conexion.prepareStatement("DELETE FROM man_incidencias WHERE id_incidencia = '"+selectedRow+"'");
            ps.executeUpdate();            
            JOptionPane.showMessageDialog(null, "Incidencia Eliminada");            
            conexion.close();
            
        } catch (Exception e) {
            Logger.getLogger(tec_screen.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jppm = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jsp_profesor = new javax.swing.JScrollPane();
        jt_tecnico = new javax.swing.JTable();
        jbtn_urgencia = new javax.swing.JButton();
        jbtn_estado = new javax.swing.JButton();
        jtxt_buscar = new javax.swing.JTextField();
        jbtn_consultar = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jmb_tecnico = new javax.swing.JMenuBar();
        jmb_mas = new javax.swing.JMenu();
        jmi_correo = new javax.swing.JMenuItem();
        jmi_addInci = new javax.swing.JMenuItem();
        jmi_helpTecnico = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INCIDENCIAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jt_tecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsp_profesor.setViewportView(jt_tecnico);

        jbtn_urgencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_urgencia.setText("Buscar por urgencia");
        jbtn_urgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_urgenciaActionPerformed(evt);
            }
        });

        jbtn_estado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_estado.setText("Buscar por estado");
        jbtn_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_estadoActionPerformed(evt);
            }
        });

        jtxt_buscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jbtn_consultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_consultar.setText("Consultar tipos");
        jbtn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_consultarActionPerformed(evt);
            }
        });

        jbtn_actualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_actualizar.setText("Actualizar Información");
        jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarActionPerformed(evt);
            }
        });

        jmb_mas.setText("Acciones");
        jmb_mas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jmi_correo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmi_correo.setText("Enviar Correo");
        jmi_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_correoActionPerformed(evt);
            }
        });
        jmb_mas.add(jmi_correo);

        jmi_addInci.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmi_addInci.setText("Nueva Incidencia");
        jmi_addInci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_addInciActionPerformed(evt);
            }
        });
        jmb_mas.add(jmi_addInci);

        jmi_helpTecnico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmi_helpTecnico.setText("Ayuda");
        jmi_helpTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_helpTecnicoActionPerformed(evt);
            }
        });
        jmb_mas.add(jmi_helpTecnico);

        jmb_tecnico.add(jmb_mas);

        setJMenuBar(jmb_tecnico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsp_profesor, javax.swing.GroupLayout.DEFAULT_SIZE, 1361, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_consultar)
                        .addGap(62, 62, 62)
                        .addComponent(jbtn_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_urgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_actualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp_profesor, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_urgencia)
                    .addComponent(jbtn_estado)
                    .addComponent(jtxt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_consultar)
                    .addComponent(jbtn_actualizar))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Item de menu para enviar correo
    private void jmi_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_correoActionPerformed
       enviarCorreo e = new enviarCorreo(this, true);
       e.setVisible(true);
    }//GEN-LAST:event_jmi_correoActionPerformed

    // Item para crear una nueva incidencia
    private void jmi_addInciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_addInciActionPerformed
        this.setVisible(false);
        tec_addIncidencia a = new tec_addIncidencia(this, true, usuario);
        a.setVisible(true);
        verIncidencias();
    }//GEN-LAST:event_jmi_addInciActionPerformed

    // Boton para mostrar informacion segun el estado que el usuario escriba
    private void jbtn_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_estadoActionPerformed
       buscadorEstado();
    }//GEN-LAST:event_jbtn_estadoActionPerformed

    // Boton para mostrar informacion segun la urgencia que el usuario escriba
    private void jbtn_urgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_urgenciaActionPerformed
        buscadorUrgencia();
    }//GEN-LAST:event_jbtn_urgenciaActionPerformed

    // Boton para consultar los tipos de estado o urgencia existentes
    private void jbtn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_consultarActionPerformed
        tipos t = new tipos(this, true);
        t.setVisible(true);
    }//GEN-LAST:event_jbtn_consultarActionPerformed

    // Boton para despues de buscar informacion vuelva a mostrar los datos principales en la tabla
    private void jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarActionPerformed
        verIncidencias();
    }//GEN-LAST:event_jbtn_actualizarActionPerformed

    private void jmi_helpTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_helpTecnicoActionPerformed
      ayuda a = new ayuda();
      a.cargarAyuda();
    }//GEN-LAST:event_jmi_helpTecnicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtn_actualizar;
    private javax.swing.JButton jbtn_consultar;
    private javax.swing.JButton jbtn_estado;
    private javax.swing.JButton jbtn_urgencia;
    private javax.swing.JMenu jmb_mas;
    private javax.swing.JMenuBar jmb_tecnico;
    private javax.swing.JMenuItem jmi_addInci;
    private javax.swing.JMenuItem jmi_correo;
    public static javax.swing.JMenuItem jmi_helpTecnico;
    private javax.swing.JPopupMenu jppm;
    private javax.swing.JScrollPane jsp_profesor;
    private javax.swing.JTable jt_tecnico;
    private javax.swing.JTextField jtxt_buscar;
    // End of variables declaration//GEN-END:variables

    // Metodo para mostrar las incidencias en el JTable
    private void verIncidencias() {        
        dtm.setNumRows(0);
        dtm.setColumnIdentifiers(new String[]{"Id Incidencia", "Nombre", "Descripción", "Decripción Técnica", "Horas", "Estado", "Fecha", "Inicio", "Final", "Urgencia", "Ubicación", "Observaciones"});        
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(dtm);
        jt_tecnico.setRowSorter(elQueOrdena);        
        String[] a = new String[12];
        Connection conexion = conectar.getConexion();
        try {
            PreparedStatement ps = conexion.prepareStatement("select m.id_incidencia, p.nombre_completo, m.descripcion, m.desc_tecnica, m.horas, e.estado, m.fecha, m.fecha_ini_rep, m.fecha_fin_rep, ur.urgencia, ub.ubicacion, m.observaciones\n"
                    + "from man_incidencias m left join fp_profesor p\n"
                    + "on p.id_profesor = m.id_profesor_crea left join man_estado e \n"
                    + "on e.id_estado = m.id_estado left join man_ubicacion ub\n"
                    + "on ub.id_ubicacion = m.id_ubicacion left join man_urgencia ur\n"
                    + "on ur.id_urgencia = m.nivel_urgencia\n");
            
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a[0] = rs.getString(1);
                a[1] = rs.getString(2);
                a[2] = rs.getString(3);
                a[3] = rs.getString(4);
                a[4] = rs.getString(5);
                a[5] = rs.getString(6);
                a[6] = rs.getString(7);
                a[7] = rs.getString(8);
                a[8] = rs.getString(9);
                a[9] = rs.getString(10);
                a[10] = rs.getString(11);
                a[11] = rs.getString(12);
                dtm.addRow(a);
            }                  
            jt_tecnico.setModel(dtm);
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(tec_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Metodo para everiguar el id del usuario correspondiente
    private void saberId() {
        Connection conexion = conectar.getConexion();
        try {
            PreparedStatement ps = conexion.prepareStatement("select id_profesor from fp_profesor where login = '" + usuario + "';");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id = rs.getString(1);
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(tec_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Metodo para el boton de buscar segun estado
    private void buscadorEstado() {
        dtm.setNumRows(0);
        dtm.setColumnIdentifiers(new String[]{"Id Incidencia", "Nombre", "Descripción", "Decripción Técnica", "Horas", "Estado", "Fecha", "Inicio", "Final", "Urgencia", "Ubicación", "Observaciones"});        
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(dtm);
        jt_tecnico.setRowSorter(elQueOrdena);        
        String buscar = jtxt_buscar.getText();        
        String[] a = new String[12];
        Connection conexion = conectar.getConexion();
        try {
            PreparedStatement ps = conexion.prepareStatement("select m.id_incidencia, p.nombre_completo, m.descripcion, m.desc_tecnica, m.horas, e.estado, m.fecha, m.fecha_ini_rep, m.fecha_fin_rep, ur.urgencia, ub.ubicacion, m.observaciones\n"
                    + "from man_incidencias m left join fp_profesor p\n"
                    + "on p.id_profesor = m.id_profesor_crea left join man_estado e \n"
                    + "on e.id_estado = m.id_estado left join man_ubicacion ub\n"
                    + "on ub.id_ubicacion = m.id_ubicacion left join man_urgencia ur\n"
                    + "on ur.id_urgencia = m.nivel_urgencia\n"
                    + "where e.estado = '"+buscar+"' order by m.id_estado");
            
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a[0] = rs.getString(1);
                a[1] = rs.getString(2);
                a[2] = rs.getString(3);
                a[3] = rs.getString(4);
                a[4] = rs.getString(5);
                a[5] = rs.getString(6);
                a[6] = rs.getString(7);
                a[7] = rs.getString(8);
                a[8] = rs.getString(9);
                a[9] = rs.getString(10);
                a[10] = rs.getString(11);
                a[11] = rs.getString(12);
                dtm.addRow(a);
            }                  
            jt_tecnico.setModel(dtm);
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(tec_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Metodo para el boton de buscar segun urgencia
    private void buscadorUrgencia() {
        dtm.setNumRows(0);
        dtm.setColumnIdentifiers(new String[]{"Id Incidencia", "Nombre", "Descripción", "Decripción Técnica", "Horas", "Estado", "Fecha", "Inicio", "Final", "Urgencia", "Ubicación", "Observaciones"});        
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(dtm);
        jt_tecnico.setRowSorter(elQueOrdena);        
        String buscar = jtxt_buscar.getText();        
        String[] a = new String[12];
        Connection conexion = conectar.getConexion();
        try {
            PreparedStatement ps = conexion.prepareStatement("select m.id_incidencia, p.nombre_completo, m.descripcion, m.desc_tecnica, m.horas, e.estado, m.fecha, m.fecha_ini_rep, m.fecha_fin_rep, ur.urgencia, ub.ubicacion, m.observaciones\n"
                    + "from man_incidencias m left join fp_profesor p\n"
                    + "on p.id_profesor = m.id_profesor_crea left join man_estado e \n"
                    + "on e.id_estado = m.id_estado left join man_ubicacion ub\n"
                    + "on ub.id_ubicacion = m.id_ubicacion left join man_urgencia ur\n"
                    + "on ur.id_urgencia = m.nivel_urgencia\n"
                    + "where ur.urgencia = '"+buscar+"' order by m.nivel_urgencia");
            
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a[0] = rs.getString(1);
                a[1] = rs.getString(2);
                a[2] = rs.getString(3);
                a[3] = rs.getString(4);
                a[4] = rs.getString(5);
                a[5] = rs.getString(6);
                a[6] = rs.getString(7);
                a[7] = rs.getString(8);
                a[8] = rs.getString(9);
                a[9] = rs.getString(10);
                a[10] = rs.getString(11);
                a[11] = rs.getString(12);
                dtm.addRow(a);
            }                  
            jt_tecnico.setModel(dtm);
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(tec_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
