/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecnico;

import administrador.add_usuario;
import administrador.ver_profesores;
import com.mycompany.mantenimiento_paula.Conectar;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import profesor.profe_addInci;
import profesor.profe_screen;

/**
 *
 * @author damA
 */
public class tec_addIncidencia extends javax.swing.JDialog {

    Conectar conectar = new Conectar();

    String usuario;
    String id;

    /**
     * Creates new form add_incidencia_tec
     */
    public tec_addIncidencia(javax.swing.JDialog parent, boolean modal, String user) {
        super(parent, modal);
        conectar.getConexion();

        usuario = user;

        initComponents();

        saberId();

        rellenar_ubicaciones();
        rellenar_estado();
        rellenar_urgencia();

        icono();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // X de la pantalla
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                tec_screen screen = new tec_screen(tec_addIncidencia.this, true, usuario);
                screen.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxta_descripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxta_descrTec = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jtxt_horas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_fecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_fechaini = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_fechafin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbo_ubis = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxta_observaciones = new javax.swing.JTextArea();
        jbtn_guardar = new javax.swing.JButton();
        jcbo_estado = new javax.swing.JComboBox<>();
        jcb_urgencia = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(909, 598));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVA INCIDENCIA");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Descripción:");

        jtxta_descripcion.setColumns(20);
        jtxta_descripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxta_descripcion.setRows(5);
        jScrollPane1.setViewportView(jtxta_descripcion);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Descripción Técnica:");

        jtxta_descrTec.setColumns(20);
        jtxta_descrTec.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxta_descrTec.setRows(5);
        jScrollPane2.setViewportView(jtxta_descrTec);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Horas:");

        jtxt_horas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Estado:");

        jtxt_fecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxt_fecha.setToolTipText("YYYY-MM-DD");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Fecha:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Fecha Inicial Reparacion:");

        jtxt_fechaini.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxt_fechaini.setToolTipText("YYYY-MM-DD");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Fecha Final Reparacion:");

        jtxt_fechafin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxt_fechafin.setToolTipText("YYYY-MM-DD");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Urgencia:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Ubicación:");

        jcbo_ubis.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbo_ubis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbo_ubisActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Observaciones:");

        jtxta_observaciones.setColumns(20);
        jtxta_observaciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxta_observaciones.setRows(5);
        jScrollPane3.setViewportView(jtxta_observaciones);

        jbtn_guardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_guardar.setText("Guardar");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        jcbo_estado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbo_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbo_estadoActionPerformed(evt);
            }
        });

        jcb_urgencia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcb_urgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_urgenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jtxt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jtxt_fechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel11))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jcbo_ubis, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jcbo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtxt_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcb_urgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn_guardar)
                                .addGap(120, 120, 120))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_fechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbo_ubis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jcb_urgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn_guardar)
                                .addGap(60, 60, 60))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        insertarIncidencia();
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    private void jcbo_ubisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbo_ubisActionPerformed
        rellenar_ubicaciones();
    }//GEN-LAST:event_jcbo_ubisActionPerformed

    private void jcbo_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbo_estadoActionPerformed
        rellenar_estado();
    }//GEN-LAST:event_jcbo_estadoActionPerformed

    private void jcb_urgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_urgenciaActionPerformed
        rellenar_urgencia();
    }//GEN-LAST:event_jcb_urgenciaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JComboBox<String> jcb_urgencia;
    private javax.swing.JComboBox<String> jcbo_estado;
    private javax.swing.JComboBox<String> jcbo_ubis;
    private javax.swing.JTextField jtxt_fecha;
    private javax.swing.JTextField jtxt_fechafin;
    private javax.swing.JTextField jtxt_fechaini;
    private javax.swing.JTextField jtxt_horas;
    private javax.swing.JTextArea jtxta_descrTec;
    private javax.swing.JTextArea jtxta_descripcion;
    private javax.swing.JTextArea jtxta_observaciones;
    // End of variables declaration//GEN-END:variables

    // Metodo para averiguar el id del usuario que se ha conectado
    private void saberId() {
        Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("select id_profesor from fp_profesor where login = '" + usuario + "';");

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                id = rs.getString(1);
            }

            conexion.close();

        } catch (SQLException ex) {
            Logger.getLogger(profe_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Metodo para poner icono al programa en esta ventana
    private void icono() {
        ImageIcon img = new ImageIcon("src\\main\\java\\resources\\icon.png");
        this.setIconImage(img.getImage());
    }

    // Metodo para insertar incidencia en la base de datos
    private void insertarIncidencia() {
        String descripcion = jtxta_descripcion.getText();
        String descrTecnico = jtxta_descrTec.getText();
        String horas = jtxt_horas.getText();
        String estado = (String) jcbo_estado.getSelectedItem();
        String fecha = jtxt_fecha.getText();
        String f_ini = jtxt_fechaini.getText();
        String f_fin = jtxt_fechafin.getText();
        String urgencia = (String) jcb_urgencia.getSelectedItem();
        String ubicacion = (String) jcbo_ubis.getSelectedItem();
        String observaciones = jtxta_observaciones.getText();

        String[] u = ubicacion.toString().split(" - ");
        String ubis = u[0];

        String[] e = estado.toString().split(" - ");
        String es = e[0];

        String[] ur = urgencia.toString().split(" - ");
        String urg = ur[0];

        Connection conexion = conectar.getConexion();

        try {
            PreparedStatement ps = conexion.prepareStatement("INSERT INTO man_incidencias(id_profesor_crea, descripcion, desc_tecnica, horas, estado, fecha, fecha_ini_rep, fecha_fin_rep, nivel_urgencia id_ubicacion, observaciones) "
                    + "VALUES('" + id + "','" + descripcion + "','" + descrTecnico + "','" + horas + "','" + es + "'," + fecha + "','" + f_ini + "','" + f_fin + "','" + urg + "','" + ubis + "','" + observaciones + "')");
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos insertados.");

            conexion.close();

        } catch (SQLException ex) {
            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }

    // Metodo para rellenar con la informacion de diferentes tipo de ubicaciones
    private void rellenar_ubicaciones() {
        Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("SELECT distinct id_ubicacion, ubicacion FROM man_ubicacion");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                jcbo_ubis.addItem(rs.getString("id_ubicacion") + " - " + rs.getString("ubicacion"));
            }

            conexion.close();

        } catch (SQLException ex) {

            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Metodo para rellenar con la informacion de diferentes tipo de estados
    private void rellenar_estado() {
        Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("SELECT distinct id_estado, estado FROM man_estado");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                jcbo_estado.addItem(rs.getString("id_estado") + " - " + rs.getString("estado"));
            }

            conexion.close();

        } catch (SQLException ex) {

            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Metodo para rellenar con la informacion de los diferentes tipos de urgencias
    private void rellenar_urgencia() {
        Connection conexion = conectar.getConexion();

        try {

            PreparedStatement ps = conexion.prepareStatement("SELECT distinct id_urgencia, urgencia FROM man_urgencia");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                jcb_urgencia.addItem(rs.getString("id_urgencia") + " - " + rs.getString("urgencia"));
            }

            conexion.close();

        } catch (SQLException ex) {

            Logger.getLogger(profe_addInci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
