/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecnico;

import com.mycompany.mantenimiento_paula.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author damA
 */
public class tipos extends javax.swing.JDialog {

    Conectar conectar = new Conectar();
    
    // Modelo de la tabla 
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form tiposUrEs
     */
    public tipos(javax.swing.JDialog parent, boolean modal) {
        
        super(parent, modal);
        
        initComponents();
        
        conectar.getConexion();
        
        mostrarTipos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jt_tipos = new javax.swing.JTable();
        jbtn_ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jt_tipos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_tipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jt_tipos);

        jbtn_ok.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_ok.setText("OK");
        jbtn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_okActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("TIPOS DE ESTADO/URGENCIA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_ok)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_ok)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Boton ok para volver a principal
    private void jbtn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_okActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_okActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_ok;
    private javax.swing.JTable jt_tipos;
    // End of variables declaration//GEN-END:variables

    // Metodo para mostrar los tipos de estado e urgencia que existen
    private void mostrarTipos() {
        dtm.setColumnIdentifiers(new String[]{"Tipos Estado", "Tipos Urgencia"});
        Connection conexion = conectar.getConexion();
        String[] a = new String[2];
        try {
            PreparedStatement ps = conexion.prepareStatement("select distinct u.urgencia, e.estado\n"
                    + "from man_urgencia u left join man_estado e\n"
                    + "on u.id_urgencia = e.id_estado");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a[0] = rs.getString(1);
                a[1] = rs.getString(2);
                dtm.addRow(a);
            }           
            jt_tipos.setModel(dtm);
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(tec_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
